Sprint 2
elagarrigue/AyDS22-AK-Winchester1 pull request #1
Opened 2022-04-13 13:20 UTC by MarianelaDiaz

2022-04-14 21:58 UTC, elagarrigue requested changes
Muy bien en general, tienen que resolver el tipo de dato date precision y otros comentarios menores.

2022-04-14 21:58 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/entities/SpotifySong.kt
> +    val releaseDatePrecision: String
Definir un enumerado `DatePrecision` para evitar el acomplamiento de lógica del servidor en la vista

2022-04-14 21:58 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/entities/SpotifySong.kt
> +    override val releaseDatePrecision: String = ""
El valor por default puede ser `DatePrecision.DATE`

2022-04-14 21:58 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/external/spotify/tracks/SpotifyToSongResolver.kt
> +        return album[RELEASE_DATE_PRECISION].asString
en este punto deben convertir el string a valor del enumerado

2022-04-14 21:58 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/local/spotify/sqldb/SpotifyLocalStorageImpl.kt
> +            put(RELEASE_DATE_PRECISION_COLUMN, song.releaseDatePrecision)
```suggestion
            put(RELEASE_DATE_PRECISION_COLUMN, song.releaseDatePrecision.ordinal)
```

2022-04-14 21:58 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/local/spotify/sqldb/SpotifyTableConstants.kt
> +            "$RELEASE_DATE_PRECISION_COLUMN string, " +
el tipo va a ser `integer`

2022-04-14 21:58 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/view/SongDateFormatImpl.kt
> +        val releaseDatePrecision = song.releaseDatePrecision
no son necesarias estas variables temporales, las propiedades son suficientemente claras. Un truco de kotlin para evitar el `song.` es utilizar el `with`:
 ```
with(song) {
   return formatterDate(releaseDate, releaseDatePrecision)
}
```

2022-04-14 21:58 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/view/SongDateFormatImpl.kt
> +            "year" -> dateFormatted = yearFormat(date)
Acá utilizaremos los valores del enumerado

2022-04-14 21:58 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/view/SongDateFormatImpl.kt
> +    }
Se puede simplificar
```suggestion
    private fun leapYear(year : Int) = ((year % 4 == 0) && (year % 100 != 0 || year % 400 == 0))
```

2022-04-16 19:06 UTC, marcovalla commented on app/src/main/java/ayds/winchester/songinfo/home/model/entities/SpotifySong.kt
> +    val releaseDatePrecision: String
Se definió el enumerado DatePrecision y se actualizo el tipo de dato de releaseDatePrecision de String a DatePrecision

2022-04-16 19:06 UTC, marcovalla commented on app/src/main/java/ayds/winchester/songinfo/home/model/entities/SpotifySong.kt
> +    override val releaseDatePrecision: String = ""
Se modificó el valor por defecto a DatePrecision.DATE

2022-04-16 19:08 UTC, marcovalla commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/external/spotify/tracks/SpotifyToSongResolver.kt
> +        return album[RELEASE_DATE_PRECISION].asString
Se modifico la funcion convirtiendo el valor String al valor del enumerado correspondiente.
Obs: Se agregó el valor DatePrecision.DATE como valor por defecto

2022-04-16 19:09 UTC, marcovalla commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/local/spotify/sqldb/SpotifyLocalStorageImpl.kt
> +            put(RELEASE_DATE_PRECISION_COLUMN, song.releaseDatePrecision)
Se modificó el codigo aplicando el cambio mencionado para almacenar el enumerado como un entero

2022-04-16 19:09 UTC, marcovalla commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/local/spotify/sqldb/SpotifyTableConstants.kt
> +            "$RELEASE_DATE_PRECISION_COLUMN string, " +
Se modificó la columna de tipo String a tipo Integer

2022-04-16 19:10 UTC, marcovalla commented on app/src/main/java/ayds/winchester/songinfo/home/view/SongDateFormatImpl.kt
> +        val releaseDatePrecision = song.releaseDatePrecision
Se actualizó la funcion descartando las variables temporales, adoptando una sintaxis mas acorde a Kotlin

2022-04-16 19:12 UTC, marcovalla commented on app/src/main/java/ayds/winchester/songinfo/home/view/SongDateFormatImpl.kt
> +            "year" -> dateFormatted = yearFormat(date)
Se modificó el metodo para poder formatear la fecha segun los valores del enumerado y no mediante un formato String

2022-04-16 19:12 UTC, marcovalla commented on app/src/main/java/ayds/winchester/songinfo/home/view/SongDateFormatImpl.kt
> +    }
Se simplificó el metodo adoptando una sintaxis mas acorde a Kotlin

2022-04-20 11:17 UTC, elagarrigue requested changes

2022-04-20 11:17 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/external/spotify/tracks/SpotifyToSongResolver.kt
> +            else -> DatePrecision.DATE
No cumple con SRP, OC. Mover a otra clase.

2022-04-21 20:58 UTC, elagarrigue approved these changes

2022-04-21 20:58 UTC, merged