Sprint 6
elagarrigue/AyDS22-AK-Winchester1 pull request #5
Opened 2022-06-07 01:41 UTC by somozaemanuel

Terminado sprint 6.

2022-06-07 14:28 UTC, elagarrigue requested changes
- En la descripción del PR listar los cambios
- No compila, ProxyWikipedia no está actualizado a los últimos cambios del submodule
- Sigue habiendo referencias a wikipedia en los paquetes del repositorio
- Implementar tests para el broker y los proxies
-

2022-06-07 14:28 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/view/MoreDetailsUiState.kt
> +    val FULL_ARTICLE_URL: String = "",
Es un propiedad, va en camelCase

2022-06-07 14:28 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/view/MoreDetailsView.kt
>          artistInfoTextView = findViewById(R.id.textPane2)
mejorar el nombre de la view `R.id.textPane2`

2022-06-07 14:28 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/model/repository/InfoRepositoryImpl.kt
>  interface InfoRepository {
CardsRepository

2022-06-07 14:28 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/model/repository/InfoRepositoryImpl.kt
> +        var cards: List<Card>? = cardLocalStorage.getCardsByName(cardName)
Es buena práctica evitar devolver null cuando se puede. En esta caso, local storage puede devolver una lista vacía

2022-06-07 14:28 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/model/repository/external/wikipedia/proxys/ProxyLastFM.kt
> +    private val lastFMService : LastFMService = LastFMInjector.lastFMService
No cumple con ID, inyectar la dependencia!! No se pueden implementar tests. Lo mismo con el resto de los proxies.

2022-06-07 18:33 UTC, marcovalla commented
> * En la descripción del PR listar los cambios
> 
>     * No compila, ProxyWikipedia no está actualizado a los últimos cambios del submodule
> 
>     * Sigue habiendo referencias a wikipedia en los paquetes del repositorio
> 
>     * Implementar tests para el broker y los proxies

ProxyWikipedia ya se encontraba actualizado con los ultimos cambios del submodulo.

2022-06-09 11:43 UTC, elagarrigue requested changes

2022-06-09 11:43 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/model/repository/local/MoreDetailsDataBase.kt
> +    fun saveArtist(artist: String?, card: Card)
save cards

2022-06-09 11:43 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/model/repository/local/database/CursorToCardMapper.kt
> +                            infoURL = getString(getColumnIndexOrThrow(ARTIST_PAGE_ID_COLUMN)),
El nombre de la columna es incorrecto

2022-06-09 11:43 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/model/repository/local/database/MoreDetailsTableConstants.kt
>  const val ARTISTS_TABLE = "artists"
cards table

2022-06-09 11:43 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/model/repository/external/proxys/ProxyLastFMInjector.kt
> +object ProxyLastFMInjector{
No hace falta más de un inyector por paquete, unificar en uno (demasiadas clases, complica la búsqueda)

2022-06-09 11:43 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/model/repository/CardsRepositoryImpl.kt
> +                }
Si ocurre una excepción en solo uno de los servicios, devuelve la lista vacía. Esto lo hablamos en el laboratorio, mover los try catch a los proxies.

2022-06-09 20:06 UTC, elagarrigue requested changes

2022-06-09 20:06 UTC, elagarrigue commented on app/src/test/java/ayds/winchester/songinfo/moredetails/model/repository/external/proxys/ProxyLastFMTest.kt
> +class ProxyLastFMTest {
Falta cubrir el caso en que el servicio dispara una excepción en los proxies

2022-06-10 19:41 UTC, marcovalla commented
Se actualizaron los injectores del **submodulo.**

2022-06-12 21:35 UTC, elagarrigue requested changes

2022-06-12 21:35 UTC, elagarrigue commented on app/src/test/java/ayds/winchester/songinfo/moredetails/model/repository/CardsRepositoryTest.kt
> +    fun `given service exception should return empty collection of artist info cards`() {
nombre del test incorrecto

2022-06-12 21:35 UTC, elagarrigue commented on app/src/test/java/ayds/winchester/songinfo/moredetails/model/repository/external/BrokerTest.kt
> +class BrokerTest{
falta cubrir el caso mixto, empty cards y cards

2022-06-12 21:35 UTC, elagarrigue commented on app/src/test/java/ayds/winchester/songinfo/moredetails/model/repository/external/proxies/ProxyNewYorkTimesTest.kt
> +
falta cubrir los casos en que el servicio retorna null

2022-06-14 11:31 UTC, elagarrigue approved these changes
Ahí quedó 👍🏽

2022-06-14 11:32 UTC, merged